#############################################################################
# Generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#  Apr 28, 2026 12:13:07 PM EDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


#######  Default Fonts ########
set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkTooltipFont
set vTcl(actual_gui_font_tooltip_name)  TkTooltipFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Absolute
set vTcl(mode) Absolute
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -menu $top.m59 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 452x514+540+126
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but53" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -compound left -default disabled \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #000000 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "+" \
        -underline -1 -width 0 -wraplength 0 
    vTcl:DefineAlias "$top.but53" "increase_button" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but52" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -compound left -cursor fleur \
        -default disabled -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -justify center -padx 1 \
        -pady 1 -relief raised -repeatdelay 0 -repeatinterval 0 -state normal \
        -text "-" -underline -1 -width 0 -wraplength 0 
    vTcl:DefineAlias "$top.but52" "decrease_button" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but49" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -compound left -default disabled \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #000000 \
        -height 26 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal \
        -text "Switch Language" -underline -1 -width 107 -wraplength 0 
    vTcl:DefineAlias "$top.but49" "lang_button" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but57" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -compound left -default disabled \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground black \
        -height 36 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal \
        -text "Manual Gate
Control" -underline -1 -width 97 -wraplength 0 
    vTcl:DefineAlias "$top.but57" "gate_button" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but58" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -compound left -default disabled \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground black \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "ON/OFF" \
        -underline -1 -width 0 -wraplength 0 
    vTcl:DefineAlias "$top.but58" "on_off_button" vTcl:WidgetProc "Toplevel1" 1
# add aa target = .top1.m59, basename = $top.m59
    menu "$top.m59" \
        -activebackground #d9d9d9 -activeborderwidth 1 \
        -activeforeground black -background #d9d9d9 -borderwidth 1 \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground black \
        -relief flat -selectcolor SystemMenuText -takefocus 0 -tearoff 0 \
        -type normal 
# add first menu widget
    ttk::label "$top.tLa55" \
        -background #ffff00 -font "TkDefaultFont" -relief flat -anchor w \
        -justify left -underline -1 -width 114 -compound left -state normal \
        -style "" 
    vTcl:DefineAlias "$top.tLa55" "led_label" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but56" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -compound left -default disabled \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground black \
        -height 36 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Silence
Alarm" \
        -underline -1 -width 97 -wraplength 0 
    vTcl:DefineAlias "$top.but56" "alarm_button" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$top.tLa54" \
        -font "TkDefaultFont" -relief flat -anchor w -justify left \
        -underline -1 -width 214 -compound left -state normal -cursor fleur \
        -style "" 
    vTcl:DefineAlias "$top.tLa54" "display_label" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.but53
    place $top.but53 \
        -in $top -x 250 -y 220 -width 47 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
# add p1 basename = $top.but52
    place $top.but52 \
        -in $top -x 150 -y 220 -width 47 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
# add p1 basename = $top.but49
    place $top.but49 \
        -in $top -x 170 -y 20 -width 107 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
# add p1 basename = $top.but57
    place $top.but57 \
        -in $top -x 270 -y 370 -width 97 -relwidth 0 -height 36 -relheight 0 \
        -anchor nw -bordermode ignore 
# add p1 basename = $top.but58
    place $top.but58 \
        -in $top -x 20 -y 480 -anchor nw -bordermode ignore 
# add p1 basename = $top.tLa55
    place $top.tLa55 \
        -in $top -x 170 -y 270 -width 114 -relwidth 0 -height 37 -relheight 0 \
        -anchor nw -bordermode ignore 
# add p1 basename = $top.but56
    place $top.but56 \
        -in $top -x 100 -y 370 -width 97 -relwidth 0 -height 36 -relheight 0 \
        -anchor nw -bordermode ignore 
# add p1 basename = $top.tLa54
    place $top.tLa54 \
        -in $top -x 120 -y 90 -width 214 -relwidth 0 -height 107 -relheight 0 \
        -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

