#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Apr 28, 2026 12:13:07 PM EDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

# from Project import prototype_support
# from Project import prototype_support
import prototype_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: prototype_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("452x514+540+126")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(0,  0)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.increase_button = tk.Button(self.top)
        self.increase_button.place(x=250, y=220, height=26, width=47)
        self.increase_button.configure(activebackground="#d9d9d9")
        self.increase_button.configure(activeforeground="black")
        self.increase_button.configure(background="#d9d9d9")
        self.increase_button.configure(compound='left')
        self.increase_button.configure(disabledforeground="#a3a3a3")
        self.increase_button.configure(foreground="#000000")
        self.increase_button.configure(highlightbackground="#d9d9d9")
        self.increase_button.configure(highlightcolor="#000000")
        self.increase_button.configure(text='''+''')

        self.decrease_button = tk.Button(self.top)
        self.decrease_button.place(x=150, y=220, height=26, width=47)
        self.decrease_button.configure(activebackground="#d9d9d9")
        self.decrease_button.configure(activeforeground="black")
        self.decrease_button.configure(background="#d9d9d9")
        self.decrease_button.configure(compound='left')
        self.decrease_button.configure(cursor="fleur")
        self.decrease_button.configure(disabledforeground="#a3a3a3")
        self.decrease_button.configure(foreground="#000000")
        self.decrease_button.configure(highlightbackground="#d9d9d9")
        self.decrease_button.configure(highlightcolor="#000000")
        self.decrease_button.configure(text='''-''')

        self.lang_button = tk.Button(self.top)
        self.lang_button.place(x=170, y=20, height=26, width=107)
        self.lang_button.configure(activebackground="#d9d9d9")
        self.lang_button.configure(activeforeground="black")
        self.lang_button.configure(background="#d9d9d9")
        self.lang_button.configure(compound='left')
        self.lang_button.configure(disabledforeground="#a3a3a3")
        self.lang_button.configure(foreground="#000000")
        self.lang_button.configure(highlightbackground="#d9d9d9")
        self.lang_button.configure(highlightcolor="#000000")
        self.lang_button.configure(text='''Switch Language''')

        self.gate_button = tk.Button(self.top)
        self.gate_button.place(x=270, y=370, height=36, width=97)
        self.gate_button.configure(activebackground="#d9d9d9")
        self.gate_button.configure(activeforeground="black")
        self.gate_button.configure(background="#d9d9d9")
        self.gate_button.configure(compound='left')
        self.gate_button.configure(disabledforeground="#a3a3a3")
        self.gate_button.configure(foreground="black")
        self.gate_button.configure(highlightbackground="#d9d9d9")
        self.gate_button.configure(highlightcolor="#000000")
        self.gate_button.configure(text='''Manual Gate
Control''')

        self.on_off_button = tk.Button(self.top)
        self.on_off_button.place(x=20, y=480, height=26, width=55)
        self.on_off_button.configure(activebackground="#d9d9d9")
        self.on_off_button.configure(activeforeground="black")
        self.on_off_button.configure(background="#d9d9d9")
        self.on_off_button.configure(compound='left')
        self.on_off_button.configure(disabledforeground="#a3a3a3")
        self.on_off_button.configure(foreground="black")
        self.on_off_button.configure(highlightbackground="#d9d9d9")
        self.on_off_button.configure(highlightcolor="#000000")
        self.on_off_button.configure(text='''ON/OFF''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        ########### start #######################
        ########### end #######################

        _style_code()
        self.led_label = tk.Label(self.top)
        self.led_label.place(x=170, y=270, height=37, width=114)
        self.led_label.configure(background="#ffff00")
        self.led_label.configure(font="TkDefaultFont")
        self.led_label.configure(relief="flat")
        self.led_label.configure(compound='left')

        self.alarm_button = tk.Button(self.top)
        self.alarm_button.place(x=100, y=370, height=36, width=97)
        self.alarm_button.configure(activebackground="#d9d9d9")
        self.alarm_button.configure(activeforeground="black")
        self.alarm_button.configure(background="#d9d9d9")
        self.alarm_button.configure(compound='left')
        self.alarm_button.configure(disabledforeground="#a3a3a3")
        self.alarm_button.configure(foreground="black")
        self.alarm_button.configure(highlightbackground="#d9d9d9")
        self.alarm_button.configure(highlightcolor="#000000")
        self.alarm_button.configure(text='''Silence
Alarm''')

        self.display_label = ttk.Label(self.top)
        self.display_label.place(x=120, y=90, height=107, width=214)
        self.display_label.configure(font="TkDefaultFont")
        self.display_label.configure(relief="flat")
        self.display_label.configure(compound='left')
        self.display_label.configure(cursor="fleur")

def start_up():
    prototype_support.main()

if __name__ == '__main__':
    prototype_support.main()




