#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Apr 28, 2026 12:13:15 PM EDT  platform: Windows NT

import random
from random import random
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import prototype   # Correct import

_debug = True  # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)

    global _top1, _w1
    _top1 = root
    _w1 = prototype.Toplevel1(_top1)

    init_dummy_logic()
    root.mainloop()


def init_dummy_logic():
    '''Sets up initial dummy states and bindings'''
    _w1.display_label.configure(text="System Ready")

    # Button bindings
    _w1.increase_button.configure(command=lambda: dummy_action("Increase Pressed"))
    _w1.decrease_button.configure(command=lambda: dummy_action("Decrease Pressed"))
    _w1.on_off_button.configure(command=toggle_led)
    _w1.alarm_button.configure(command=lambda: dummy_action("Alarm Silenced"))


def dummy_action(msg):
    print(f"DEBUG: {msg}")
    _w1.display_label.configure(text=msg)
    toggle_led()


def toggle_led():
    current_bg = _w1.led_label.cget("background")
    new_color = "#00ff00" if current_bg == "#ffff00" else "#ffff00"
    _w1.led_label.configure(background=new_color)
    print(f"LED Toggle: {new_color}")


if __name__ == '__main__':
    prototype.start_up()

